#!/bin/bash
set -euo pipefail
#https://wiki.archlinux.org/index.php/DeveloperWiki:Building_in_a_Clean_Chroot

destiny="/home/${USER}/XRAY/xray-core/x86_64/"

search1="calamares"
search=$search1

tput setaf 2
echo "#############################################################################################"
echo "#########        Let us build the package "$(basename `pwd`)
echo "#############################################################################################"
tput sgr0

updpkgsums

makepkg --sign

echo "Moving created files to $destiny"
echo "#############################################################################################"

if ls ${search}*pkg.tar.zst 1> /dev/null 2>&1; then
    mv ${search}*pkg.tar.zst "$destiny"
    mv ${search}*pkg.tar.zst.sig "$destiny"
else
    echo "No package files found for $search."
    exit 1
fi

echo "Cleaning up"
echo "#############################################################################################"
echo "deleting unnecessary folders"
echo "#############################################################################################"

rm -rf pkg src

echo "deleting unnecessary files"
echo "#############################################################################################"

rm -rf calamares

tput setaf 8
echo "#############################################################################################"
echo "###################                       build done                   ######################"
echo "#############################################################################################"
tput sgr0
